version: '3.8'

services:
  postgres:
    image: mirror.gcr.io/library/postgres:14-alpine
    container_name: payment-postgres
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment -d payment_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: mirror.gcr.io/flyway/flyway:latest
    container_name: payment-flyway
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../src/main/resources/db/migration:/flyway/sql
    command: -url=jdbc:postgresql://postgres:5432/payment_db -user=payment -password=payment123 migrate
    profiles:
      - migrate

volumes:
  postgres-data:
